config/routes.rb
Rails.application.routes.draw do

  get 'contactrequest/index'
  get 'contactrequest/new'
  # session routes
# resources :sessions, only: [:post, :destroy]
get "/login", to: "sessions#login", as: "login"
post '/login', to:"sessions#create"
delete "/logout", to: "sessions#destroy"



root "users#home"
# user routes
get "/users", to: "users#index", as: "users"
get "/users/new", to:"users#new", as: "new_user"
get "/users/:id", to: "users#show", as: "user"
post "/users", to: "users#create"
get "/users/:id/edit", to:"users#edit"
patch "/users/:id", to:"users#update"
delete "/users/:id", to:"users#destroy", as:"destroy_user"
 # interests routes
get '/interests', to:"interests#index", as:"interests"
get '/interests/new', to:"interests#new"
get '/interests/:id', to:"interests#show", as:"interest"
post '/interests', to:"interests#create"
# get '/interests', to:"interests#index"
# resources :user_interests, only: [:index, :new, :show, :edit]

# user_interests
# get '/interests', to:"interests#index", as:"interests"
# get '/interests/new', to:"interests#new"
# get '/interests/:id', to:"interests#show", as:"interest"
post '/user_interests', to:"user_interests#create"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_request.rb
class ContactRequest < ApplicationRecord
  belongs_to :user
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_many :user_interests
  has_many :users, through: :user_interests
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :seeker, class_name: "User"
  belongs_to :matcher, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
has_many :user_interests
has_many :interests, through: :user_interests
has_many :seeker_matches, class_name: "Match", foreign_key: "seeker_id"
has_many :matcher_matches, class_name: "Match", foreign_key: "matcher_id"
has_many :seekers, through: :seeker_matches, source: :seeker
has_many :matchers, through: :matcher_matches, source: :matcher
#validates_presence_of :email, :password
#validates_uniqueness_of :email
# validates_confirmation_of :password
# validate :current_user
has_secure_password
# def current_user
#   if session[:user_id]
#       User.find(session[:user_id])
#   else
#       false
#   end
end
  # def picture?
  #   if self.photo = ""
  #     self.photo = "/assets/avtar.jpg"
  #   end
  # end

  # def user_identity_and_interests
  #   @users = UserInterest.all.select{|use| use.hobbie_id == session[:user_id]}
  #
  # end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
  belongs_to :user
  belongs_to :interest

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    if session[:user_id]
        User.find(session[:user_id])
    else
        false
    end
end
#
end

app/controllers/contactrequest_controller.rb
class ContactrequestController < ApplicationController
  def index
  end

  def new
    @contactrequest = ContactRequest.new
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  def index
    @interests = Interest.all
  end

  def new
    @interests = Interest.all
    @interest = Interest.new
  end

  def create
    @interest = Interest.create(params[:id])
  end
  def edit
  end

  def show
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
  end

  def new
  end


  def edit
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    # session[:user_id] = @user.id
    # redirect_to @user
  end

  def create
    @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])

            session[:user_id] = @user.id

            redirect_to user_path(@user)
        else
            flash[:message] = "Stop trying to be someone else"
            render :login
        end
  end

  def destroy
     session[:user_id] = nil
  end
end

app/controllers/user_interests_controller.rb
class UserInterestsController < ApplicationController
  def index
    @user_interests = UserInterest.all
  end

  def new
    @user_interest = UserInterest.new
  end

  def create
    # @user_interest = UserInterest.create
    i = Interest.find_by(hobbies: params[:Interests])
    UserInterest.create(user: current_user, interest: i)
    redirect_to user_path(current_user)
  end

  def edit
  end

  def show
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def profile
  #   @users = User.all
  #   @users.find(session[:matcher_id])
  #   session[:matcher_id] = @user
  #   redirect_to ""
  # end
  def home
    @user = User.find(session[:user_id])
    @users = User.all.select{|u| u.relationship_type == @user[:relationship_type]}
    render :show
  end

  def new
    @user= User.new
    @relationship_choice = ["Friendship", "Possibility of Serious", "Marriage", "Hookups", "Be Partners"]
    @choice = ["Male", "Female", "Non-binary"]

  end

  def create
    @user = User.create(user_params)

    # @user.picture?
    session[:user_id] = @user.id
    redirect_to interests_new_path
     # @user = User.new(user_params)
     # session[:user_id] = @user.id
  end

  def edit
    @user = User.find(session[:user_id])
    @relationship_choice = ["Friendship", "Possibility of Serious", "Marriage", "Hookups", "Be Partners"]
    @choice = ["Male", "Female", "Non-binary"]
  end

  def update
    @user = User.find(session[:user_id])
    # byebug
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def show
    @interests = Interest.all
    @user = User.find(params[:id])
    @users = User.all.select{|u| u != current_user && @user.interests == u.interests}
    # redirect_to user_path(@user.id)
  end

def destroy
  @user = User.find(session[:user_id])
  @user.destroy
  flash[:message]= "Account deleted!"
  redirect_to "/login"
end
# u.id != session[:user_id]
  private

  def user_params

    params.require(:user).permit(:full_name, :user_name, :email, :password, :identity, :location, :date_of_birth, :partner, :relationship_type, :photo)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactrequest_helper.rb
module ContactrequestHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_interests_helper.rb
module UserInterestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contactrequest/index.html.erb
<h1>Contactrequest#index</h1>
<p>Find me in app/views/contactrequest/index.html.erb</p>

app/views/contactrequest/new.html.erb
<h1>Contact Form</h1>
<%= form_for @contactrequest do |f| %>
<%= f.label  %>

<% end %>

app/views/interests/edit.html.erb
<h1>Interests#edit</h1>
<p>Find me in app/views/interests/edit.html.erb</p>

app/views/interests/index.html.erb
<h1>Interests#index</h1>
<p>Find me in app/views/interests/index.html.erb</p>

app/views/interests/new.html.erb
<h1>Interests</h1>
<p>Please, pick at least two:</p>
<div class="form_row">
  <%= form_tag '/user_interests' do %>
    <label for="Interests">Interests:</label>
    <% [ 'Gardening', 'Painting', 'Rescue Animals', 'Visit Animal Sanctuaries', 'Writing', 'Basketball', 'Coding', 'Just Chill', 'MMA', 'Baseball', 'Going to different events' ].each do |int| %>
      <br><%= radio_button_tag 'Interests', int, @interest == int %>
      <%= int.humanize %>

    <% end %>
    <br>
    <br>
    <%= submit_tag "Submit" %>
    <% end %>
</div>

app/views/interests/show.html.erb
<h1>Interests#show</h1>
<p>Find me in app/views/interests/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kouple</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="assets/Kouple.png"></a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="/users/<%=session[:user_id]%>">My Profile</a></li>
          <li><a href="/users/:id/edit">Edit </a></li>

          <li><a href="/login">Log Out</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
    </div>



    <%= yield %>
  </body>
</html>

app/views/matches/edit.html.erb
<h1>Matches#edit</h1>
<p>Find me in app/views/matches/edit.html.erb</p>

app/views/matches/index.html.erb
<h1>Matches#index</h1>
<p>Find me in app/views/matches/index.html.erb</p>

app/views/matches/new.html.erb
<h1>Matches#new</h1>
<p>Find me in app/views/matches/new.html.erb</p>

app/views/matches/show.html.erb
<h1>Matches#show</h1>
<p>Find me in app/views/matches/show.html.erb</p>

app/views/user_interests/edit.html.erb
<h1>UserInterests#edit</h1>
<p>Find me in app/views/user_interests/edit.html.erb</p>

app/views/user_interests/index.html.erb
<h1>UserInterests#index</h1>
<p>Find me in app/views/user_interests/index.html.erb</p>

app/views/user_interests/new.html.erb
<h1>Your Main Interest</h1>

app/views/user_interests/show.html.erb
<h1>UserInterests#show</h1>
<p>Find me in app/views/user_interests/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit Your Information Here</h1>
<div class="form">
<%= form_for @user do |f| %>
<%= f.label "Full Name:" %>
<%= f.text_field :full_name %>
<br>
<br>
<%= f.label "User Name:" %>
<%= f.text_field :user_name %>
<br>
<br>
<%= f.label "Email:" %>
<%= f.text_field :email %>
<br>
<br>
<%= f.label "Password:" %>
<%= f.password_field :password %>
<br>
<br>
<%= f.label "Identity:" %>
<%= f.collection_select :identity, @choice, :to_s, :to_s, prompt: "Please, choose" %>
<br>
<br>
<%= f.label "Location:" %>
<%= f.text_field :location %>
<br>
<br>
<%= f.label "DOB:" %>
<%= f.date_field :date_of_birth %>
<br>
<br>
<%= f.label "Interested in: " %>
<%= f.collection_select :partner, @choice, :to_s, :to_s, prompt: "Please, choose"%>
<br>
<br>
<%= f.label "Looking for:" %>
<%= f.collection_select :relationship_type, @relationship_choice, :to_s, :to_s, prompt: "Please, choose" %>
<br>
<br>
<%= collection_select :post, :interest_id, Interest.all, :id, :hobbies, prompt: "Please, select" %>
<br>
<br>
<%= f.label "Photo" %>
<%= f.text_field :photo %>

<%= f.button "Update" %>
<% end %>
<%= button_to "Delete", destroy_user_path(@user), method: :delete %>
</div>

app/views/users/new.html.erb
<h1>Application Form</h1>
<div class="form">
<%= form_for @user do |f| %>
<%= f.label "Full Name:" %>
<%= f.text_field :full_name %>
<br>
<br>
<%= f.label "User Name:" %>
<%= f.text_field :user_name %>
<br>
<br>
<%= f.label "Email:" %>
<%= f.text_field :email %>
<br>
<br>
<%= f.label "Password:" %>
<%= f.password_field :password %>
<br>
<br>
<%= f.label "Identity:" %>
<%= f.collection_select :identity, @choice, :to_s, :to_s, prompt: "Please, choose" %>
<br>
<br>
<%= f.label "Location:" %>
<%= f.text_field :location %>
<br>
<br>
<%= f.label "DOB:" %>
<%= f.date_field :date_of_birth %>
<br>
<br>
<%= f.label "Interested in: " %>
<%= f.collection_select :partner, @choice, :to_s, :to_s, prompt: "Please, choose"%>
<br>
<br>
<%= f.label "Looking for:" %>
<%= f.collection_select :relationship_type, @relationship_choice, :to_s, :to_s, prompt: "Please, choose" %>
<br>
<br>
<%= f.label "Photo" %>
<%= f.text_field :photo %>
<%= f.submit "Submit"%>
<% end %>

</div>

app/views/users/profile.html.erb
<h1> <%= @user.name %></h1>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<div class="profile">


<%= image_tag "#{@user.photo}", :size => "220x180"%>
<br>
<br>
User name: <%= @user.user_name %>
<br>
<br>
Email: <%= @user.email %>
<br>
<br>
The List of My Matches:
<%@users.each do |us| %>
<p><%= link_to us.full_name, user_path(us.id) %></p>
<% end %>
</div>